### PR TITLE
Tags plugin: Fix routes for tags #180

### PR DESCRIPTION
**Pull request by rachit-iam**

### CODE REVIEW

**Comment by dominikbraun** [comment]
Your first change actually looked fine. The imports have to look like so:

```go
import (
	"path/filepath"
	"strings"

	"github.com/verless/verless/model"
	"github.com/verless/verless/tree"
)
```

Because we group the imports by standard library and third-party packages. If you want to, you may install [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) and configure your IDE to do this automatically.

**Comment by dominikbraun** [comment]
Fine, now you just need to format the code with go fmt using `go fmt ./...`. Which IDE or editor are you using? This should be enabled for any Go editor by default. 🤔

**Comment by rachit-iam** [comment]
> Fine, now you just need to format the code with go fmt using `go fmt ./...`. Which IDE or editor are you using? This should be enabled for any Go editor by default. 🤔
I am using vscode , is there any readme of how to run or test the project?
Meanwhile, all checks have been passed, thanks for the comments.

**Comment by dominikbraun** [comment]
> I am using vscode

If you have the official Go extension for VS Code, you can configure the formatting like so: https://code.visualstudio.com/docs/languages/go#_formatting

> is there any readme of how to run or test the project?

There aren't docs for this yet, but it is simple. Running a command:

```
go run cmd/verless/main.go <command> <options>
```

The `go run cmd/verless/main.go` is the part which would be `verless`. For example, running `verless build` is nothing else than `go run cmd/verless/main.go build`.

Testing is even simpler:

```
go test ./...
```

**Review by dominikbraun — APPROVED** [review]
Looks good to me, thanks for your contribution! 🥳

**Pull request merged**
