### PR TITLE
Preserve assets directory structure.

### LINKED ISSUE #225: Structure of /assets directory should be preserved on copy
### Description

Each theme has an `assets` directory. When building the site, the `assets` directory of the active theme will be copied to the project root, making it available as `/assets` in the HTML.

Unfortunately, verless only copies the files but doesn't preserve the directory structure: `assets/css/style.css` will be copied as `/assets/style.css` instead of `/assets/css/style.css`.

IMO, this is because `fileOnly` is set to `true` - which makes `fs.CopyFromOS` only copy the file in the target directory `/assets`, without preserving the directory structure.

https://github.com/verless/verless/blob/d370ee33bfd9bb9b1c7f01890d0b82589a213bf8/writer/writer.go#L180-L184

I think this could be fixed by simply removing `fileOnly: true`.

**Verify if the fix works**

To test if a fix works, create a CSS file `themes/default/assets/css/test.css` in the `example` project, run `verless serve example` and check if `localhost:8080/assets/css/test.css` exists.

### PR DESCRIPTION
**Pull request by mo3taz1705**
`Fixes #225`.

### CODE REVIEW

**Review by dominikbraun — APPROVED** [review]
LGTM, thanks :+1:

**Comment by mo3taz1705** [comment]
@dominikbraun can you please add the "hacktoberfest-accepted" label to the PR, so that it would be counted in my progress in the hacktober fest challenge?

**Comment by dominikbraun** [comment]
My mistake was to remove the `hacktoberfest` topic from the repository too early. I added it again and since this PR has been merged, it should count again now. Please let me know if it works 👍

**Comment by mo3taz1705** [comment]
Thanks a lot. yes it has been counted now. it is waiting to be reviewed in around 13 days.

**Pull request merged**
