### PR TITLE
Add Robots field to front matter, closes #240

### LINKED ISSUE #240: Add Robots Front Matter field
There should be a new field in the YAML Front Matter called `Robots`. This field can be added analogous to existing fields like `Title`.

### PR DESCRIPTION
**Pull request by FelixMohr**
Hi,

I have implemented #240. I have also added the Robots field to meta.go for usage in the list pages. Please let me know if any adaptions are necessary.

### CODE REVIEW

**Comment by aligator** [comment]
Thanks for your PRs!
We will review them the next days :-)

**Comment by aligator** [comment]
@dominikbraun 
I am not sure how we really want it to be:
@FelixMohr has currently implemented it the simplest way possible: just a string which can be passed and may look like this:
```yaml
Robots: <meta name="robots" content="noindex" /><meta name="AdsBot-Google" content="noindex" />
```
which can be used in the templates like this:
```html
<head>
{{.Meta.Robots}}
</head>
```
This may be ok, as it is also the most flexible way. But then it is so flexible that I would not call it `.Robots` as it is possible to apply any head-tags there.

So there are some questions:
1. do we need something that flexible?
2. if no: as I can see it this is always a key-value tag. So we could use a map instead similar to this:
```yaml
Robots: 
    robots: noindex
    AdsBot-Google: noindex
```
which would generate this:
```html
<head>
...
<meta name="robots" content="noindex" />
<meta name="AdsBot-Google" content="noindex" />
....
</head>
```
3. as it may be needed to add more than one tag (like in the example above) should we use a slice instead of a single string? (Or a map like I showed in 2.)

**Comment by dominikbraun** [comment]
So the idea for the `Robots` field comes from [Espresso](https://github.com/dominikbraun/espresso) where it has been used like this:

```yaml
---
# Markdown Front Matter
Robots: noindex, nofollow
---
````

```html
<!-- Template -->
<meta name="robots" content="{{.Article.Robots}}" />
```

The implementation at that time - and issue #240 - didn't even have multiple meta tags in mind. I'd suggest to just leave it as it is, or represent the robot information using the map syntax. Note that this would require a dedicated `Robots` struct to allow type-safe access in templates, e.g. `{{.Page.Robots.AdsBotGoogle}}`.

```yaml
---
# Markdown Front Matter
Robots:
    robots: noindex, nofollow
    AdsBotGoogle: nofollow
---
```

**Comment by alinnert** [comment]
@dominikbraun even a map could be misused like so:

~~~ md
Robots:
    viewport: width=device-width, initial-scale=1
~~~

to generate:

~~~ html
<meta name="viewport" content="width=device-width, initial-scale=1">
~~~

There's nothing special about the robots meta tags. There are a lot more possible values for `<meta>` that work all the same way. So, imo, it would make more sense to make it a `Meta` field instead:

~~~ md
Meta:
    viewport: width=device-width, initial-scale=1
    robots: noindex, nofollow
~~~

Unless you have another plan how meta tags in general can be provided.

As a side note: Besides `<meta name content>` there's also `<meta http-equiv content>` which works very similar syntax wise.

**Comment by dominikbraun** [comment]
@alinnert Thanks! I consider your suggested solution the best approach here.

The obvious challenge I faced was to allow type-safe access in templates (like `{{.Page.Meta.Robots}}`). However, I've come to realize that this is neither necessary nor possible: As a theme creator, you won't be able to know which `<meta>` tags are required or provided by the user, so you would have to include them by ranging over `{{.Page.Meta}}` anyway.

```html
<head>
    {{range $name, $content := .Page.Meta}}
        <meta name="{{$name}}" content="{{$content}}" />
    {{end}}
</head>
```

@FelixMohr Sorry for not pointing this out clearly. Would you be comfortable with changing `Robots` to `Meta` as a `map[string]string`?

I've created a `readMap` function, and you can use it to populate the `Meta` map as follows:

```go
readMap(metadata["Meta"], func(key, val interface{}) {
	page.Meta[key.(string)] = val.(string)
})
```

Just make sure to merge `master` in your branch and initialize `page.Meta` at some point.

@aligator PTAL

**Comment by aligator** [comment]
LGTM

**Review by dominikbraun — CHANGES_REQUESTED** [review]
Sorry again for not planning this feature properly. But the steps described in [my comment](https://github.com/verless/verless/pull/247#issuecomment-740752440) shouldn't take too long :)

**Comment by FelixMohr** [comment]
Sure, I'll adapt the implementation during the next days.

**Review by dominikbraun — APPROVED** [review]
LGTM, thanks! 👍

**Comment by dominikbraun** [comment]
Thanks once again for building this!

**Pull request merged**
